# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-04 15:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('totalExpense', models.IntegerField(default=12, max_length=200)),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenseTitle', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('amount', models.IntegerField(max_length=200)),
                ('paymentType', models.CharField(choices=[('CREDITCARD', 'creditCard'), ('DEBITCARD', 'debitCard'), ('NETBANKING', 'netBanking'), ('CASH', 'cash'), ('OTHERS', 'others')], default='CREDITCARD', max_length=10)),
                ('creditCardOrBankAccountNo', models.CharField(max_length=200)),
                ('expenseType', models.CharField(choices=[('FAMILY', 'family'), ('PERSONAL', 'personal'), ('BUSINESS', 'business'), ('OTHERS', 'others')], default='FAMILY', max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('vendorName', models.CharField(max_length=200)),
                ('invoiceId', models.IntegerField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
